services:
  - type: web
    name: main_project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: main_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: main_project_db
          property: connectionString

databases:
  - name: main_project_db
    databaseName: main_project
    user: main_project_user