# Generated by Django 5.1.5 on 2025-01-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('youtube', 'YouTube')], max_length=10),
        ),
    ]
