# Generated by Django 5.1.5 on 2025-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0005_extractedtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('youtube', 'YouTube')], max_length=10),
        ),
    ]
