# Generated by Django 5.1.5 on 2025-05-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0006_alter_uploadedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('paddle_plan_id', models.CharField(max_length=100, unique=True)),
                ('pdf_uploads_per_month', models.IntegerField()),
                ('pdf_max_size_mb', models.IntegerField()),
                ('pdf_max_pages', models.IntegerField()),
                ('audio_uploads_per_month', models.IntegerField()),
                ('audio_max_size_mb', models.IntegerField()),
                ('audio_max_length_min', models.IntegerField()),
                ('youtube_links_per_month', models.IntegerField()),
                ('youtube_max_length_min', models.IntegerField()),
                ('quizzes_per_month', models.IntegerField()),
                ('summary_regenerations_per_file', models.IntegerField()),
                ('chatbot_messages_per_file', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('paddle_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowbite.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
