# Generated by Django 5.1.5 on 2025-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0007_plan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('name', 'billing_period')},
        ),
    ]
