# Generated by Django 5.1.5 on 2025-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0008_plan_billing_period_alter_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_webhook_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='pause_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'In Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='trialing', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
