# Generated by Django 5.1.5 on 2025-06-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0009_alter_plan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_period',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='paddle_plan_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
