# Generated by Django 5.1.5 on 2025-06-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0010_plan_is_free_alter_plan_billing_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
