# Generated by Django 5.1.5 on 2025-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowbite', '0011_alter_usersubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
