"""
Django settings for main_project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
from dotenv import load_dotenv
load_dotenv()

import os
import certifi
os.environ['SSL_CERT_FILE'] = certifi.where()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d)@r43sfdo&nx3h5p)z-g^qnc74z^3rzvf^8n6ei8v@sa4v5q1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'knowbite',
    'result',
    'users',
    'crispy_forms',
    'markdownify',
    'sendgrid'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
    
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSP_FRAME_ANCESTORS = [
    "'self'",
    "https://*.paddle.com",
    "https://*.paddlecheckout.com",
    "https://*.paddlepayments.com",
    "https://*.paddleapi.com",
    "https://*.billing.paddle.com",
    "https://buy.paddle.com",
]
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'dashboard'

LOGIN_URL = 'login'

ASSEMBLYAI_API_KEY = os.getenv('ASSEMBLYAI_API_KEY')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Paddle configuration
PADDLE_VENDOR_ID = os.getenv('PADDLE_ID')
PADDLE_API_KEY = os.getenv('PADDLE_API_KEY')
PADDLE_CLIENT_TOKEN = os.getenv('PADDLE_CLIENT_TOKEN')  # Add this line

# These should match the paddle_plan_id values you set in the admin for each plan
PADDLE_BASIC_MONTHLY_PLAN_ID = os.getenv('PADDLE_BASIC_MONTHLY_PLAN_ID')
PADDLE_BASIC_YEARLY_PLAN_ID = os.getenv('PADDLE_BASIC_YEARLY_PLAN_ID')
PADDLE_PRO_MONTHLY_PLAN_ID = os.getenv('PADDLE_PRO_MONTHLY_PLAN_ID')
PADDLE_PRO_YEARLY_PLAN_ID = os.getenv('PADDLE_PRO_YEARLY_PLAN_ID')

# Set to True for sandbox/testing, False for production
PADDLE_SANDBOX = True

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'jasonachin33@example.com>'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')

# Optional but recommended for development
#SENDGRID_SANDBOX_MODE_IN_DEBUG = True
#EMAIL_HOST = 'smtp.sendgrid.net'
#EMAIL_HOST_USER = 'apikey'  # This stays as 'apikey'
#EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True  # Use SSL since STARTTLS (587) failed
#EMAIL_USE_TLS = False  

#DEFAULT_FROM_EMAIL = 'jasonachin33@gmail.com'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
